<?php

namespace Cscc\DataBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ExtensionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtensionRepository extends DocumentRepository
{
}